name: Java CI Pipeline

on:
  push:

jobs:

  validation-and-security:

    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # 1. CHECKOUT CODE
      # ==========================================

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Checkout
        run: |
          pwd
          ls -ltr

      # ==========================================
      # 2. SECRET SCAN
      # ==========================================

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # ==========================================
      # 3. DEPENDENCY INSTALL
      # ==========================================

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Download Dependencies
        run: mvn dependency:resolve

      # ==========================================
      # 4. SCA (OWASP)
      # ==========================================

      - name: Run OWASP Dependency Check
        run: mvn dependency-check:check

      - name: Verify OWASP Report
        run: |
          ls -ltr target/
          find target -name "*dependency*" || true

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-report
          path: |
            target/dependency-check-report.html
            target/dependency-check-report.xml
            target/dependency-check-report.json