name: Java CI Pipeline

on:
  push:

jobs:

  validation-and-security:

    runs-on: ubuntu-latest

    steps:

      # ==========================================
      # 1. CHECKOUT CODE
      # ==========================================

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Checkout
        run: |
          pwd
          ls -ltr
          tree . || true

      # ==========================================
      # 2. SECRET SCAN
      # ==========================================

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # ==========================================
      # 3. DEPENDENCY INSTALL
      # ==========================================

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Download Dependencies
        run: mvn dependency:resolve

      # ==========================================
      # 4. SCA (OWASP)
      # ==========================================

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "java-maven-ci-demo"
          path: "."
          format: "HTML"

      - name: Verify OWASP Report
        run: |
          find . -type f | grep dependency-check || true

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-report
          path: reports/