name: Java DevSecOps CI Pipeline

on:
  push:

jobs:

  # ==========================================================
  # JOB-1 VALIDATION & SECURITY
  # ==========================================================

  validation-and-security:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Checkout
        run: |
          pwd
          ls -ltr

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Download Dependencies
        run: mvn dependency:resolve
      
      - name: Run OWASP Dependency Check
        run: mvn dependency-check:check

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-report
          path: target/dependency-check-report.html